### PR TITLE
21 landing page

### PR DESCRIPTION
**Pull request by ayanahye**
Changes
- Created the landing page on both desktop and mobile view
- Added Navbar and made responsive on mobile

To do:
- I am having troubles adding the banner
- I am not sure which font we are using 
- Verify design of navigation menu with design team

### CODE REVIEW

**Comment by ayanahye** [comment]
Forgot to add
- Need to get links on navbar to link to pages
- Need to get real images (will export as svg when we have them, but for now I am just using placeholder png's)

**Comment by ChrisFong604** [comment]
Thanks Ayana, I'm going to make and issue for adding the background colour and font-settings. Once it has bee committed to the repo, you can go ahead and integrate it with your PR

**Comment by brendanshen24** [comment]
Hi Ayana, code looks good to me! Perhaps in the future, it would be good to change to base the screen resizing breakpoint on the ones Chris set in the tailwind config instead of hardcoding the px value in the Landing.jsx. It might also be nice to maybe decrease the width between the divs containing the "hours, total hackers, $ in prizes and # of diverse projects" text boxes in the future to closer match the Figma mockup. Great work!

**Comment by davidrobertlowe** [comment]
Closing, brought these changes into development

**Pull request closed without merging**
